name: Shabaz Badshah dot com
description: Hey there, my name is Shabaz Badshah and this is my little home on the internet.
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
# If you are serving to gh-pages, change baseurl to repository name with a /
# i.e.  /PersonalWebsite from ""
baseurl: ""
github-url: "https://shabazbadshah.github.io"
permalink: '/:categories/:title/'
plugins:
  - jekyll-seo-tag

social:
  name: Shabaz Badshah
  links:
    - http://linkedin.com/in/shabaz-badshah/
    - https://github.com/ShabazBadshah